"""
Pipeline 02 - Clean univariate logistic analysis on real training windows.

Input:
    data/nuevo_intento_processed_features_windows_real.csv

Output:
    data/nuevo_intento_results_fase1_windows_clean.csv
"""

from __future__ import annotations

import warnings
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedGroupKFold, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from pipeline_01_feature_engineering import (
    CLINICAL_METADATA_PATH,
    REAL_OUTPUT_PATH,
    create_composite_target,
    valid_predictor_columns,
)


OUTPUT_PATH = Path("data/nuevo_intento_results_fase1_windows_clean.csv")
RANDOM_STATE = 42


@dataclass(frozen=True)
class PatientSplit:
    """Patient-level split mapped to window rows."""

    train_df: pd.DataFrame
    test_df: pd.DataFrame
    train_records: set[int]
    test_records: set[int]


@dataclass(frozen=True)
class UnivariateResult:
    """One univariate feature result."""

    feature: str
    auroc_cv: float
    odds_ratio: float
    ci_lower: float
    ci_upper: float
    p_value: float


def load_real_windows() -> pd.DataFrame:
    """Load clean real windows generated by pipeline 01."""
    if not REAL_OUTPUT_PATH.exists():
        raise FileNotFoundError(f"Run pipeline_01_feature_engineering.py first: {REAL_OUTPUT_PATH}")
    return pd.read_csv(REAL_OUTPUT_PATH)


def patient_level_split(df: pd.DataFrame) -> PatientSplit:
    """Split unique patients 70/30 before selecting windows."""
    clinical = pd.read_csv(CLINICAL_METADATA_PATH)
    clinical["target"] = create_composite_target(clinical)
    train_records, test_records = train_test_split(
        clinical["record"],
        test_size=0.30,
        stratify=clinical["target"],
        random_state=RANDOM_STATE,
    )
    train_set = set(train_records.astype(int))
    test_set = set(test_records.astype(int))
    train_df = df[df["record"].astype(int).isin(train_set)].copy()
    test_df = df[df["record"].astype(int).isin(test_set)].copy()
    overlap = set(train_df["record"].astype(int)).intersection(set(test_df["record"].astype(int)))
    if overlap:
        raise RuntimeError(f"Patient leakage detected: {sorted(overlap)[:5]}")
    return PatientSplit(train_df, test_df, train_set, test_set)


def candidate_features(train_df: pd.DataFrame) -> list[str]:
    """Valid non-constant numeric predictors."""
    columns = valid_predictor_columns(train_df)
    numeric_columns = train_df[columns].select_dtypes(include=[np.number]).columns
    return [column for column in numeric_columns if train_df[column].nunique(dropna=True) >= 2]


def _safe_exp(value: float) -> float:
    """Numerically safe odds-ratio exponentiation."""
    if value > np.log(np.finfo(float).max):
        return float("inf")
    if value < np.log(np.finfo(float).tiny):
        return 0.0
    return float(np.exp(value))


def grouped_cv_auroc(feature: str, train_df: pd.DataFrame, n_splits: int = 5) -> float:
    """Univariate AUROC using patient-grouped stratified CV."""
    x = train_df[[feature]]
    y = train_df["target"].astype(int)
    groups = train_df["record"].astype(int)
    group_targets = train_df[["record", "target"]].drop_duplicates("record")
    splits = min(n_splits, int(group_targets["target"].value_counts().min()))
    if splits < 2 or train_df[feature].nunique(dropna=True) < 2:
        return np.nan

    cv = StratifiedGroupKFold(n_splits=splits, shuffle=True, random_state=RANDOM_STATE)
    aucs: list[float] = []
    for train_idx, valid_idx in cv.split(x, y, groups):
        model = Pipeline(
            steps=[
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
                (
                    "logit",
                    LogisticRegression(
                        solver="liblinear",
                        class_weight="balanced",
                        random_state=RANDOM_STATE,
                    ),
                ),
            ]
        )
        model.fit(x.iloc[train_idx], y.iloc[train_idx])
        probabilities = model.predict_proba(x.iloc[valid_idx])[:, 1]
        if y.iloc[valid_idx].nunique() >= 2:
            aucs.append(float(roc_auc_score(y.iloc[valid_idx], probabilities)))
    return float(np.mean(aucs)) if aucs else np.nan


def clustered_logit_stats(feature: str, train_df: pd.DataFrame) -> tuple[float, float, float, float]:
    """Fit univariate Logit with cluster-robust SE by patient."""
    if train_df[feature].nunique(dropna=True) < 2:
        return np.nan, np.nan, np.nan, np.nan
    imputer = SimpleImputer(strategy="median")
    scaler = StandardScaler()
    x_scaled = scaler.fit_transform(imputer.fit_transform(train_df[[feature]])).reshape(-1)
    design = sm.add_constant(x_scaled, has_constant="add")
    y = train_df["target"].to_numpy(dtype=float)
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            model = sm.Logit(y, design)
            result = model.fit(
                disp=False,
                maxiter=250,
                cov_type="cluster",
                cov_kwds={"groups": train_df["record"].astype(int).to_numpy()},
            )
    except Exception:
        return np.nan, np.nan, np.nan, np.nan

    coef = float(result.params[1])
    ci = result.conf_int(alpha=0.05)
    return _safe_exp(coef), _safe_exp(float(ci[1, 0])), _safe_exp(float(ci[1, 1])), float(result.pvalues[1])


def analyze_feature(feature: str, train_df: pd.DataFrame) -> UnivariateResult:
    """Run grouped AUROC and clustered inference for one feature."""
    odds_ratio, ci_lower, ci_upper, p_value = clustered_logit_stats(feature, train_df)
    return UnivariateResult(
        feature=feature,
        auroc_cv=grouped_cv_auroc(feature, train_df),
        odds_ratio=odds_ratio,
        ci_lower=ci_lower,
        ci_upper=ci_upper,
        p_value=p_value,
    )


def run_fase1() -> pd.DataFrame:
    """Execute clean Phase 1."""
    df = load_real_windows()
    split = patient_level_split(df)
    features = candidate_features(split.train_df)
    print(
        f"Train/test records: {len(split.train_records)}/{len(split.test_records)}; "
        f"windows: {len(split.train_df)}/{len(split.test_df)}"
    )
    print(f"Valid predictors evaluated: {len(features)}")

    rows = [analyze_feature(feature, split.train_df) for feature in features]
    results = pd.DataFrame(
        [
            {
                "Feature": row.feature,
                "AUROC_CV": row.auroc_cv,
                "Odds_Ratio": row.odds_ratio,
                "CI_Lower": row.ci_lower,
                "CI_Upper": row.ci_upper,
                "P_Value": row.p_value,
            }
            for row in rows
        ]
    ).sort_values(["AUROC_CV", "P_Value"], ascending=[False, True], na_position="last")
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    results.to_csv(OUTPUT_PATH, index=False)
    print("\nTop 10 clean univariate predictors:")
    print(results.head(10).to_string(index=False))
    print(f"\nSaved: {OUTPUT_PATH}")
    return results


def main() -> None:
    """CLI entrypoint."""
    run_fase1()


if __name__ == "__main__":
    main()
