"""
Pipeline 00 - Generate synchronized synthetic UC signals.

The current root synthetic folder contains FHR bootstrap files generated by
03_extract_metadata.py, but no UC files. This script replays the exact
stationary-bootstrap index sequence used for the saved FHR files and applies
those same indices to the source UC signal. That adds synchronized
data/synthetic/{syn_id}_uc.npy files without changing the existing FHR files.

It intentionally verifies that the replayed FHR equals the saved FHR before
writing each UC file.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from tqdm import tqdm


RAW_DIR = Path("data/raw")
SYNTH_DIR = Path("data/synthetic")
SYNTHETIC_METADATA_PATH = Path("data/dataset_synthetic.csv")
MANIFEST_PATH = Path("data/nuevo_intento/synthetic_uc_manifest.csv")

SEED = 42
N_MULTIPLIER = 2
MEAN_BLOCK = 240
FHR_MIN = 60.0
FHR_MAX = 200.0
UC_MAX = 200.0


def clean_fhr(signal: np.ndarray) -> np.ndarray:
    """Match the FHR cleaning used by 03_extract_metadata.py."""
    arr = signal.copy().astype(np.float32)
    arr[(arr < FHR_MIN) | (arr > FHR_MAX)] = np.nan
    nans = np.isnan(arr)
    if nans.all():
        return np.full_like(arr, 140.0)
    if not nans.any():
        return arr
    idx = np.arange(len(arr))
    valid = ~nans
    arr[nans] = np.interp(idx[nans], idx[valid], arr[valid])
    return arr


def clean_uc(signal: np.ndarray) -> np.ndarray:
    """Conservative UC cleaning before applying synchronized bootstrap indices."""
    arr = signal.copy().astype(np.float32)
    arr[(arr < 0) | (arr > UC_MAX)] = np.nan
    nans = np.isnan(arr)
    if nans.all():
        return np.zeros_like(arr)
    if not nans.any():
        return arr
    idx = np.arange(len(arr))
    valid = ~nans
    arr[nans] = np.interp(idx[nans], idx[valid], arr[valid])
    return arr


def stationary_indices(n_samples: int, mean_block: int = MEAN_BLOCK) -> np.ndarray:
    """Replay the stationary bootstrap index generator used for root FHR files."""
    p_new_block = 1.0 / mean_block
    out: list[int] = []
    pos = int(np.random.randint(0, n_samples))
    while len(out) < n_samples:
        out.append(pos % n_samples)
        pos = int(np.random.randint(0, n_samples)) if np.random.rand() < p_new_block else pos + 1
    return np.asarray(out[:n_samples], dtype=np.intp)


def load_source_pair(record: str) -> tuple[np.ndarray, np.ndarray]:
    """Load and clean the source FHR/UC pair, trimmed to common length."""
    fhr_path = RAW_DIR / f"{record}_fhr.npy"
    uc_path = RAW_DIR / f"{record}_uc.npy"
    if not fhr_path.exists() or not uc_path.exists():
        raise FileNotFoundError(f"Missing raw pair for record {record}")
    fhr = clean_fhr(np.load(fhr_path))
    uc = clean_uc(np.load(uc_path))
    n = min(len(fhr), len(uc))
    return fhr[:n], uc[:n]


def generate_synthetic_uc() -> pd.DataFrame:
    """Generate synchronized UC files for every row in data/dataset_synthetic.csv."""
    if not SYNTHETIC_METADATA_PATH.exists():
        raise FileNotFoundError(f"Missing {SYNTHETIC_METADATA_PATH}")
    metadata = pd.read_csv(SYNTHETIC_METADATA_PATH)
    expected_ids = set(metadata["record"].astype(str))

    source_records = sorted(metadata["source_record"].astype(int).astype(str).unique())
    np.random.seed(SEED)
    rows: list[dict[str, float | int | str]] = []
    counter = 0

    for source_record in tqdm(source_records, desc="Generating synchronized synthetic UC"):
        fhr, uc = load_source_pair(source_record)
        for bootstrap_idx in range(N_MULTIPLIER):
            syn_id = f"syn_{counter:05d}"
            if syn_id not in expected_ids:
                raise RuntimeError(f"Unexpected synthetic id order: {syn_id}")

            idx = stationary_indices(len(fhr))
            replayed_fhr = fhr[idx].astype(np.float32)
            saved_fhr_path = SYNTH_DIR / f"{syn_id}_fhr.npy"
            if not saved_fhr_path.exists():
                raise FileNotFoundError(f"Missing saved FHR: {saved_fhr_path}")
            saved_fhr = np.load(saved_fhr_path)
            if replayed_fhr.shape != saved_fhr.shape or not np.allclose(replayed_fhr, saved_fhr, equal_nan=True):
                raise RuntimeError(
                    f"Bootstrap replay mismatch for {syn_id}; refusing to write unsynchronized UC."
                )

            uc_syn = uc[idx].astype(np.float32)
            uc_path = SYNTH_DIR / f"{syn_id}_uc.npy"
            np.save(uc_path, uc_syn)
            valid = ~(np.isnan(replayed_fhr) | np.isnan(uc_syn))
            corr = np.nan
            if int(valid.sum()) > 10 and float(np.nanstd(replayed_fhr[valid])) > 0 and float(np.nanstd(uc_syn[valid])) > 0:
                corr = float(np.corrcoef(replayed_fhr[valid], uc_syn[valid])[0, 1])
            rows.append(
                {
                    "record": syn_id,
                    "source_record": int(source_record),
                    "bootstrap_idx": bootstrap_idx,
                    "n_samples": int(len(uc_syn)),
                    "uc_mean": float(np.nanmean(uc_syn)),
                    "uc_std": float(np.nanstd(uc_syn)),
                    "uc_min": float(np.nanmin(uc_syn)),
                    "uc_max": float(np.nanmax(uc_syn)),
                    "uc_nan_pct": float(np.isnan(uc_syn).mean() * 100.0),
                    "fhr_uc_corr": corr,
                    "uc_path": str(uc_path),
                }
            )
            counter += 1

    manifest = pd.DataFrame(rows)
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    manifest.to_csv(MANIFEST_PATH, index=False)
    return manifest


def main() -> None:
    """CLI entrypoint."""
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    manifest = generate_synthetic_uc()
    print(f"Synthetic UC files written: {len(manifest)}")
    print(f"Manifest: {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
